# Your project's server will run on proxy
PROXY: "http://writenator.local"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Path to source folder
  src: "assets/src"
  # Paths to fonts
  fonts:
    - "assets/src/fonts/**/*"
    - "vendor/bower-asset/font-awesome/fonts/**/*"
  # Paths to images
  images:
    - "assets/src/img/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/bower-asset/font-awesome/scss"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "vendor/bower-asset/bootstrap/dist/js/bootstrap.js"
    - "node_modules/apexcharts/dist/apexcharts.js"
